version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solaris_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network
  app:
    container_name: solaris
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      NODE_ENV: production
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: solaris_db
      TYPEORM_PORT: 5432
      TYPEORM_ENTITIES: dist/entity/**/*.js
      TYPEORM_ENTITIES_DIR: dist/entity
      JWT_SECRET: gVBnHbJLlN3hRe88JRgl4vIJHPvD5T7uc7i3WQwcGqA=
      STRIPE_SECRET_KEY: sk_test_51PiWSSRuDuHPl5ylAagZGq15cYiSJ7LsUyAjakm0FIfTtJ7HrRqJwdoed7Eh117B5evp2qnIxgngmbPueqqVwoze00KPBWXb71
    depends_on:
      - db
    networks:
      - todo-network

networks:
  todo-network:

volumes:
  postgres_data:

